export const carBrandsAndModels: Record<string, string[]> = {
    "Toyota": ["Camry", "Corolla", "RAV4", "Land Cruiser", "Hilux", "Yaris", "Prado", "Avensis", "Auris", "Prius", "Highlander"],
    "Honda": ["Civic", "Accord", "CR-V", "HR-V", "Pilot", "Fit", "Jazz", "Odyssey", "Insight"],
    "Ford": ["Focus", "Fiesta", "Mustang", "Explorer", "Escape", "F-150", "Mondeo", "Kuga", "Fusion", "Ranger", "Transit", "Tourneo"],
    "Chevrolet": ["Cruze", "Malibu", "Impala", "Equinox", "Tahoe", "Silverado", "Camaro", "Aveo", "Lacetti", "Captiva", "Suburban"],
    "Nissan": ["Sentra", "Altima", "Maxima", "Rogue", "Pathfinder", "Qashqai", "X-Trail", "Leaf", "Juke", "Micra", "Navara", "Patrol"],
    "BMW": ["3 Series", "5 Series", "7 Series", "1 Series", "4 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "M3", "M4", "M5"],
    "Mercedes-Benz": ["A-Class", "B-Class", "C-Class", "E-Class", "S-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "G-Class", "Sprinter", "Vito", "V-Class"],
    "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "TT", "e-tron"],
    "Volkswagen": ["Golf", "Passat", "Polo", "Tiguan", "Touareg", "Jetta", "Transporter", "Caddy", "Arteon", "Amarok", "Crafter", "Multivan", "Caravelle"],
    "Hyundai": ["Elantra", "Sonata", "Tucson", "Santa Fe", "Accent", "Creta", "Kona", "Ioniq", "i10", "i20", "i30", "Palisade", "Matrix"],
    "Kia": ["Rio", "Forte", "Optima", "Sportage", "Sorento", "Soul", "Ceed", "Cerato", "Stinger", "Picanto", "Carnival", "K5"],
    "Mazda": ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-30", "CX-5", "CX-7", "CX-9", "MX-5", "BT-50"],
    "Subaru": ["Impreza", "Legacy", "Outback", "Forester", "Crosstrek", "WRX", "XV", "Ascent"],
    "Lexus": ["IS", "ES", "GS", "LS", "RX", "NX", "UX", "GX", "LX", "LC", "RC"],
    "Volvo": ["S40", "S60", "S90", "V40", "V60", "V90", "XC40", "XC60", "XC90"],
    "Porsche": ["911", "Cayenne", "Macan", "Panamera", "Taycan", "Boxster", "Cayman"],
    "Skoda": ["Octavia", "Superb", "Fabia", "Kodiaq", "Karoq", "Kamiq", "Rapid", "Scala", "Yeti", "Roomster"],
    "Renault": ["Clio", "Megane", "Kaptur", "Duster", "Logan", "Sandero", "Trafic", "Master", "Kangoo", "Kadjar", "Koleos", "Scenic", "Laguna"],
    "Peugeot": ["208", "308", "408", "508", "2008", "3008", "5008", "Partner", "Boxer", "Expert", "Traveller"],
    "Citroen": ["C3", "C4", "C5", "C-Elysee", "Berlingo", "Jumper", "Jumpy", "SpaceTourer", "C5 Aircross"],
    "Fiat": ["500", "Panda", "Tipo", "Ducato", "Doblo", "Punto", "Fiorino", "Scudo", "Freemont"],
    "Opel": ["Astra", "Corsa", "Insignia", "Mokka", "Zafira", "Vivaro", "Vectra", "Omega", "Meriva", "Antara", "Combo", "Crossland", "Grandland"],
    "Mitsubishi": ["Lancer", "Outlander", "Pajero", "Pajero Sport", "L200", "ASX", "Colt", "Galant", "Eclipse Cross"],
    "Suzuki": ["Swift", "Vitara", "SX4", "Jimny", "Grand Vitara", "Ignis", "Kizashi", "Baleno"],
    "Land Rover": ["Range Rover", "Range Rover Sport", "Range Rover Evoque", "Range Rover Velar", "Discovery", "Discovery Sport", "Defender"],
    "Jeep": ["Wrangler", "Cherokee", "Grand Cherokee", "Compass", "Renegade", "Gladiator"],
    "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck"],
    "Dacia": ["Logan", "Sandero", "Duster", "Dokker", "Lodgy"],
    "Seat": ["Ibiza", "Leon", "Ateca", "Tarraco", "Arona", "Toledo", "Altea"],
    "Mini": ["Cooper", "Clubman", "Countryman"],
    "Acura": ["MDX", "RDX", "TLX", "ILX", "ZDX"],
    "Infiniti": ["Q50", "Q60", "Q70", "QX50", "QX55", "QX60", "QX70", "QX80", "FX", "EX"],
    "Jaguar": ["XE", "XF", "XJ", "F-Pace", "E-Pace", "I-Pace", "F-Type"],
    "Alfa Romeo": ["Giulia", "Stelvio", "Giulietta", "Mito", "159", "Tonale"],
    "Chrysler": ["300", "Pacifica", "Voyager", "PT Cruiser", "Town & Country"],
    "Dodge": ["Charger", "Challenger", "Durango", "Journey", "Ram", "Caravan", "Caliber", "Dart"],
    "ZAZ": ["Lanos", "Sens", "Forza", "Vida", "Tavria", "Slavuta"],
    "Daewoo": ["Lanos", "Sens", "Matiz", "Nexia", "Nubira", "Espero", "Leganza", "Tacuma"],
    "Lada": ["Granta", "Vesta", "Niva", "Kalina", "Priora", "Largus", "2109", "21099", "2110", "2111", "2115", "XRAY"],
    "Geely": ["Emgrand", "Coolray", "Atlas", "Tugella", "CK", "MK"],
    "Chery": ["Tiggo", "Amulet", "Kimo", "QQ", "M11", "Elara", "Jaggi"],
    "Haval": ["H6", "H9", "Jolion", "Dargo", "H2", "F7"],
    "Great Wall": ["Hover", "Wingle", "Pegasus", "Safe", "Voleex"],
    "BYD": ["F3", "Tang", "Han", "Song", "Yuan", "Dolphin"],
    "SsangYong": ["Rexton", "Kyron", "Korando", "Actyon", "Tivoli"],
    "Smart": ["Fortwo", "Forfour"],
    "GMC": ["Sierra", "Yukon", "Acadia", "Terrain", "Canyon"],
    "Lincoln": ["Navigator", "Aviator", "Corsair", "Nautilus", "Continental", "MKZ"],
    "Cadillac": ["Escalade", "XT5", "XT6", "CT4", "CT5", "ATS", "CTS", "SRX"],
    "Genesis": ["G70", "G80", "G90", "GV70", "GV80"],
    "Polestar": ["1", "2", "3", "4", "5"],
    "Rivian": ["R1T", "R1S"],
    "Lucid": ["Air"],
    "Maserati": ["Ghibli", "Quattroporte", "Levante", "Grecale", "GranTurismo"],
    "Bentley": ["Bentayga", "Continental GT", "Flying Spur"],
    "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Dawn", "Cullinan"],
    "Ferrari": ["488", "F8", "Portofino", "Roma", "SF90", "812", "Purosangue"],
    "Lamborghini": ["Huracan", "Aventador", "Urus", "Revuelto"],
    "Aston Martin": ["DB11", "Vantage", "DBS", "DBX"],
    "McLaren": ["570S", "720S", "Artura", "GT", "750S"],
    "Zeekr": ["001", "007", "009", "X"],
    "Li Auto": ["L7", "L8", "L9", "One"],
    "Voyah": ["Free", "Dream", "Passion"],
    "Changan": ["CS35 Plus", "CS55 Plus", "CS75 Plus", "UNI-K", "UNI-V", "UNI-T", "Eado"],
    "Exeed": ["LX", "TXL", "VX", "RX"],
    "Jetour": ["Dashing", "X70", "X90 Plus", "T2"],
    "GAC": ["GS8", "GS5", "M8", "Aion S", "Aion Y"],
    "Omoda": ["C5", "S5"],
    "Tank": ["300", "400", "500"],
    "Rover": ["75", "45", "25", "Streetwise"],
    "Saab": ["9-3", "9-5", "900", "9000"],
    "Lancia": ["Delta", "Ypsilon", "Thema", "Kappa"],
    "Isuzu": ["D-Max", "MU-X", "Trooper", "Rodeo"],
    "Hummer": ["H1", "H2", "H3", "EV"],
    "Tata": ["Nexon", "Harrier", "Safari", "Tiago", "Punch"],
    "Mahindra": ["XUV700", "Scorpio", "Thar", "Bolero"],
};

export const carYears = Array.from({ length: new Date().getFullYear() - 1989 }, (_, i) => String(new Date().getFullYear() - i));
